version: '3.8'

services:
  backend:
    build:
      context: ./api
    command: npm run dev
    volumes:
      - ./api:/app
    working_dir: /app
    environment:
      - DATABASE_URL=file:/app/dev.db
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build:
      context: .
    command: npm run dev
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./api/dev.db:/data/dev.db
    command: tail -f /dev/null
    # SQLite is file-based, so this is just for persistence

# Notes:
# - The backend service expects a DATABASE_URL for Prisma/SQLite.
# - The frontend expects VITE_API_URL to point to the backend.
# - For production, use a real database (e.g., Postgres) and production build commands.
# - You may need to adjust Dockerfiles for both frontend and backend for best results.
